### PR TITLE
Fix @GrailsCompileStatic on domain objects with inner classes

### LINKED ISSUE #12461: Validation is not applied when using @GrailsCompileStatic on domains with inner Enum
### Expected Behavior

When validating a domain object that is annotated with `@GrailsCompileStatic`, and that has an inner `Enum`, the validation rules in the constraints block of the domain object should be followed.

### Actual Behaviour

The validation rules are not applied.

### Steps To Reproduce

1. Create a domain class annotated with @GrailsCompileStatic and that has an inner Enum and some validation rules.
2. Write a test that tests the validation rules.

or clone the example application and run the tests.

### Environment Information

- Operating System: tested on Ubuntu 20.04
- JDK Version: tested with 8 and 11

### Example Application

https://github.com/matrei/grails-compile-static-validation-bug

### Version

5.1.5

### PR DESCRIPTION
**Pull request by darxriggs**
Fixes #12461.

### CODE REVIEW

**Comment by darxriggs** [comment]
I would like to have some suggestions on the tests. They are covering the changes and would fail without them. But I think there should be better ways. Maybe they could even be integrated into the existing `GrailsCompileStaticCompilationErrorsSpec` and `GrailsTypeCheckedCompilationErrorsSpec` files.

File: grails-test-suite-uber/src/test/groovy/grails/compiler/DomainClassWithInnerClassUsingStaticCompilationSpec.groovy [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+    void 'a domain class marked with @GrailsCompileStatic containing an inner class and a "mapping" block'() {
+        expect: 'the configuration from the "mapping" closure is available'
+            SomeClass.mapping instanceof Closure
+            SomeClass.mappingClosureCalled
+    }
+
+    @Issue('https://github.com/grails/grails-core/issues/12461')
+    void 'a domain class marked with @GrailsCompileStatic containing an inner class and a "namedQueries" block'() {
+        setup:
+            SomeClass.getNamedQuery('test')
```
Comment (darxriggs) [inline grails-test-suite-uber/src/test/groovy/grails/compiler/DomainClassWithInnerClassUsingStaticCompilationSpec.groovy:29]: This is required in contrast to the other tests as the `namedQueries` closure seems only to be evaluated when the first named query is accessed and not when the class is compiled.

File: grails-test-suite-uber/src/test/groovy/grails/compiler/DomainClassWithInnerClassUsingStaticCompilationSpec.groovy [hunk 2]
```diff
@@ -0,0 +1,60 @@
...
+import spock.lang.Issue
+import spock.lang.Specification
+
+class DomainClassWithInnerClassUsingStaticCompilationSpec extends Specification implements DomainUnitTest<SomeClass> {
+
+    @Issue('https://github.com/grails/grails-core/issues/12461')
+    void 'a domain class marked with @GrailsCompileStatic containing an inner class and a "constraints" block'() {
+        expect: 'the configuration from the "constraints" closure is available'
+            SomeClass.constraints instanceof Closure
+            SomeClass.constraintsClosureCalled
```
Comment (darxriggs) [inline grails-test-suite-uber/src/test/groovy/grails/compiler/DomainClassWithInnerClassUsingStaticCompilationSpec.groovy:16]: Another way could be to actually define a constraint, create an entity, call `entity.validate()` and check for e.g.             `SomeClass.getConstrainedProperties().containsKey('some')` or even `entity.errors['some']` or something else. But I think this would involve more components that could break in other ways.

File: grails-test-suite-uber/src/test/groovy/grails/compiler/DomainClassWithInnerClassUsingStaticCompilationSpec.groovy [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+    }
+
+    @Issue('https://github.com/grails/grails-core/issues/12461')
+    void 'a domain class marked with @GrailsCompileStatic containing an inner class and a "namedQueries" block'() {
+        setup:
+            SomeClass.getNamedQuery('test')
+
+        expect: 'the configuration from the "namedQueries" closure is available'
+            SomeClass.namedQueries instanceof Closure
+            SomeClass.namedQueriesClosureCalled
```
Comment (darxriggs) [inline grails-test-suite-uber/src/test/groovy/grails/compiler/DomainClassWithInnerClassUsingStaticCompilationSpec.groovy:33]: Another way could be to actually define a named query, call `SomeClass.getNamedQuery('some')` and verify that the result is not `null`. But I think this would involve more components that could break in other ways.

File: grails-test-suite-uber/src/test/groovy/grails/compiler/DomainClassWithInnerClassUsingStaticCompilationSpec.groovy [hunk 4]
```diff
@@ -0,0 +1,60 @@
...
+        expect: 'the configuration from the "constraints" closure is available'
+            SomeClass.constraints instanceof Closure
+            SomeClass.constraintsClosureCalled
+    }
+
+    @Issue('https://github.com/grails/grails-core/issues/12461')
+    void 'a domain class marked with @GrailsCompileStatic containing an inner class and a "mapping" block'() {
+        expect: 'the configuration from the "mapping" closure is available'
+            SomeClass.mapping instanceof Closure
+            SomeClass.mappingClosureCalled
```
Comment (darxriggs) [inline grails-test-suite-uber/src/test/groovy/grails/compiler/DomainClassWithInnerClassUsingStaticCompilationSpec.groovy:23]: I have not found a working alternative in a `DomainUnitTest` to check any side effect on the entity instance or class based on something defined in a `mapping` block . The idea could be to set e.g. `table`, `version` or `comment`.

**Comment by darxriggs** [comment]
@puneetbehl Could you have a look and suggest improvements for the tests or mention someone who could?
