### PR TITLE
Filter order values should not be fixed and should be relative to requirements of Spring Boot.

### LINKED ISSUE #13797: 7.0 Filter Order needs to be Reconsidered
Grails 7 should play well with Spring auto configurations without having to specify overriding properties.

The [current location](https://github.com/spring-projects/spring-boot/blob/005ea963079b76cf3e5315eae1318036226eaee4/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/SecurityProperties.java#L56-L61) for the Spring Security filter is  `-100`

`SecurityProperties`
```java
public static final int DEFAULT_FILTER_ORDER = OrderedFilter.REQUEST_WRAPPER_FILTER_MAX_ORDER - 100;
```

```java
interface OrderedFilter {
    int REQUEST_WRAPPER_FILTER_MAX_ORDER = 0;
}
```

but the grailsWebRequestFilter is applied at `OrderedFilter.REQUEST_WRAPPER_FILTER_MAX_ORDER + 30`
which by default puts it after the Spring Security Filter

In the comments of the [Spring Security Core plugin](https://github.com/grails/grails-spring-security-core/blob/896ec4b5da16098dfe1bc96dd5710ae79ba061f5/plugin/src/main/groovy/grails/plugin/springsecurity/SpringSecurityCoreGrailsPlugin.groovy#L220-L235)

It states
```java
// The filter chain has to be after grailsWebRequestFilter, but its order changed
// in 3.1 (from Ordered.HIGHEST_PRECEDENCE + 30 (-2147483618) to
// FilterRegistrationBean.REQUEST_WRAPPER_FILTER_MAX_ORDER + 30 (30))
```

so the recommended approach should be to change the grailsWebRequestFilter to 
`OrderedFilter.REQUEST_WRAPPER_FILTER_MAX_ORDER - 110`

which would allow Grails app using Spring Security auto configuration to configure without the need for customization. 

https://github.com/grails/grails-core/blob/0342bd126723d9f77f88f715c3fdfa2a5a1c0d5f/grails-plugin-controllers/src/main/groovy/org/grails/plugins/web/controllers/ControllersGrailsPlugin.groovy#L105-L114

### PR DESCRIPTION
**Pull request by codeconsole**
Fixes #13797

This will evolve, but it is good to get the process started.

It was place in grails-controllers because that is where the used filters are instantiated.  The other possible location is grails-bootstrap.    These are the only 2 locations that depend on spring boot autoconfigure.   This needs to be based on spring boot autoconfigure in case at some point Spring decides to change the default value (A situation like this broke the Grails Spring Security Core plugin which was previously dependent on fixed numerical values that became outdated )

Asset pipeline [PR](https://github.com/bertramdev/asset-pipeline/pull/356) should be merged after this is accepted.
Sitemesh plugin will be updated after this is accepted.

### CODE REVIEW

**Review by jamesfredley — APPROVED** [review]
Given: 

SecurityProperties.DEFAULT_FILTER_ORDER = -100
OrderedFilter.REQUEST_WRAPPER_FILTER_MAX_ORDER = 0

and the lowest int is run first

this puts these in the right order and fixed relative to when the Spring Security Filter Chain runs.

File: grails-plugin-controllers/src/main/groovy/org/grails/config/http/GrailsFilters.java [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+import org.springframework.boot.autoconfigure.security.SecurityProperties;
+
+/**
+ * Stores the default order numbers of all Grails filters for use in configuration.
+ * These filters are run prior to the Spring Security Filter Chain which is at DEFAULT_FILTER_ORDER
```
Comment (matrei) [inline grails-plugin-controllers/src/main/groovy/org/grails/config/http/GrailsFilters.java:22]: Do you want to add `@since` and `@author`?

File: grails-plugin-controllers/src/main/groovy/org/grails/config/http/GrailsFilters.java [hunk 2]
```diff
@@ -0,0 +1,48 @@
+package org.grails.config.http;
```
Comment (matrei) [inline grails-plugin-controllers/src/main/groovy/org/grails/config/http/GrailsFilters.java]: I think it is better/more common to put the package below the license header.

**Review by matrei — APPROVED** [review]

File: grails-plugin-controllers/src/main/groovy/org/grails/config/http/GrailsFilters.java (hunk 2 above)
Comment (codeconsole) [reply grails-plugin-controllers/src/main/groovy/org/grails/config/http/GrailsFilters.java]: moved

File: grails-plugin-controllers/src/main/groovy/org/grails/config/http/GrailsFilters.java (hunk 1 above)
Comment (codeconsole) [reply grails-plugin-controllers/src/main/groovy/org/grails/config/http/GrailsFilters.java:22]: added since. don't care about author
