### PR TITLE
fix: configure Micronaut annotation processor and CLASSIC boot loader automatically

### LINKED ISSUE #11599: Spring Boot Dev Tools breaks Micronaut introspection
Adding Spring Boot Dev Tools may cause breaking `Class.isInstanceof(Object)` method which is for example used by Micronaut introspection.

The Grails 3 template should either not contain the Spring Boot Dev Tools as a dependency

or

There should be a warning (ideally inside the ` build.gradle` file directly) to remove the dependency if the problem with introspection or any similar issue appears.

### Steps to Reproduce

1. Generate a new Grails 4 project
2. Add dependency to `micronaut-newrelic` https://github.com/agorapulse/micronaut-newrelic
3. Add dependency to `grails-console` https://plugins.grails.org/plugin/sheehan/console
4. Create `UserDigestInsightEvent` event (see below)
5. Run the application
6. Run the script in the Grails console

**UserDigestInsightEvent**
```groovy
class UserDigestInsightEvent implements NewRelicInsightsEvent {

    final String eventType = 'BarometerUserDigestEvent'

    Long userId
    String email
    String status

}
```

**Test Script**
```
ctx.newRelicInsightsService.createEvent(
    new UserDigestInsightEvent(userId: 1, email: "test", status: "TEST")
)
```

### Expected Behaviour

The code is executed without any errors and logs the event into the console.

### Actual Behaviour

Micronaut exception is thrown:

```
java.lang.IllegalArgumentException: Invalid bean [agorapulse.newrelic.UserDigestInsightEvent@3c3edaa8] for type: class agorapulse.newrelic.UserDigestInsightEvent
io.micronaut.core.beans.AbstractBeanProperty.get(AbstractBeanProperty.java:111)
com.agorapulse.micronaut.newrelic.BeanIntrospectionEventPayloadExtractor.lambda$extractPayload$1(BeanIntrospectionEventPayloadExtractor.java:46)
java.util.Optional.map(Optional.java:215)
com.agorapulse.micronaut.newrelic.BeanIntrospectionEventPayloadExtractor.extractPayload(BeanIntrospectionEventPayloadExtractor.java:46)
com.agorapulse.micronaut.newrelic.AsyncNewRelicInsightsService.createEvent(AsyncNewRelicInsightsService.java:51)
io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:147)
io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:60)
io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:123)
io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
Script1.run(Script1.groovy:12)
```

### Environment Information

- **Operating System**: Darwin  19.6.0
- **Grails Version:** 4.0.1
- **Micronaut Version:** 1.2.11
- **JDK Version:** Java(TM) SE Runtime Environment (build 1.8.0_212-b10)

### LINKED ISSUE #15207: Using grails-micronaut will not let you run java --jar build/libs/app.jar
### Expected Behavior

That I can start a vanilla app with the `org.apache.grails:grails-micronaut`  plugin.
It will run using
```
./gradlew bootRun
```

### Actual Behaviour

When I create a vanilla Grails app in forge, and try to run it, I get the following exception:

```
io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.context.event.ApplicationEventPublisher<io.micronaut.context.event.StartupEvent>] exists. 
        at io.micronaut.context.DefaultBeanContext.newNoSuchBeanException(DefaultBeanContext.java:2804)
        at io.micronaut.context.DefaultApplicationContext.newNoSuchBeanException(DefaultApplicationContext.java:338)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2767)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1781)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:855)
        at io.micronaut.context.BeanLocator.getBean(BeanLocator.java:97)
        at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1867)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:368)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:225)
        at io.micronaut.spring.boot.starter.MicronautImportRegistrar.registerBeanDefinitions(MicronautImportRegistrar.java:128)
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromRegistrars$1(ConfigurationClassBeanDefinitionReader.java:409)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
```

### Steps To Reproduce

```
grails-forge-cli create-app --servlet=tomcat --jdk=17 --gorm=hibernate --test=spock --features=grails-micronaut com.example.app.grails-micronaut-app
cd grails-micronaut-app
./gradlew assemble
java -jar build/libs/grails-micronaut-app-0.1.war
```

### Environment Information

- OS: Ubuntu 24.04
- JDK 17.0.15-librca

### Example Application

https://github.com/sbglasius/grails-micronaut-app

### Version

7.0.1

### LINKED ISSUE #15211: Groovy Incremental Compilation does not work with Grails-micronaut
### Issue description

See https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/906  

We need to not use annotation processors and use bean reflection instead.

### PR DESCRIPTION
**Pull request by jamesfredley**
## Summary

Fixes two Micronaut integration bugs by automating configuration that previously required manual `build.gradle` setup, resolves a Forge CI failure caused by spring-boot-devtools incompatibility, and adds a Groovy-only test module proving annotation processors are auto-applied:

- **#15207** - `java -jar` broken for grails-micronaut apps due to Spring Boot 3.2+ default loader incompatibility
- **#15211** - Java `@Singleton` beans not registered when using Groovy incremental compilation (missing annotation processor)
- **Groovy-only validation** - New test module confirms `grails-micronaut` works without explicit `annotationProcessor` dependencies or Java source files

### Issue #15207 - `java -jar` fails with `NoClassDefFoundError`

Spring Boot 3.2+ changed the default `LoaderImplementation` from `CLASSIC` to a new implementation. The new loader is incompatible with Micronaut-Spring's classpath scanning mechanism (`MicronautImportRegistrar`), causing `NoClassDefFoundError` at runtime when running a packaged JAR/WAR via `java -jar`.

### Issue #15211 - Java `@Singleton` beans silently ignored

Groovy sources use `micronaut-inject-groovy` AST transforms to generate `BeanDefinitionReference` classes. However, Java sources in a Grails project require the `micronaut-inject-java` annotation processor on the `annotationProcessor` configuration. Without it, Java beans annotated with `@Singleton`, `@Factory`, etc. are silently ignored - no compile error, just missing beans at runtime.

### GrailsGradlePlugin (`configureMicronaut()`)

1. **Annotation processor** - Automatically adds `micronaut-inject-java` + `jakarta.annotation-api` to the `annotationProcessor` configuration, scoped to the Micronaut platform BOM. This only affects `compileJava` tasks (Groovy sources continue using AST transforms via `compileOnlyApi`).

2. **CLASSIC loader** - Configures `bootJar` and `bootWar` tasks with `LoaderImplementation.CLASSIC` as a convention default (overridable by users). This ensures `java -jar` works correctly with Micronaut-Spring's classpath scanning.

### Groovy-Only Micronaut Validation

New `grails-test-examples/micronaut-groovy-only/` module with **zero Java files** and **zero explicit `annotationProcessor` dependencies** proves that the Grails Gradle plugin auto-applies the required annotation processors when `grails-micronaut` is on the classpath. The Gradle output confirms: `Micronaut Support Detected for grails-test-examples-micronaut-groovy-only`.

### Forge

- Adds the missing `bootWar` CLASSIC loader configuration to match the existing `bootJar` configuration in Forge-generated `build.gradle` files.
- `SpringBootDevTools.shouldApply()` now returns `false` when `GrailsMicronaut` is selected, preventing the DefaultFeature from being auto-applied and triggering `GrailsMicronautValidator`'s incompatibility check.

### Housekeeping

- Adds Apache license header to `GrailsMicronautValidator.java`
- Replaces `// TODO:` with `// See:` to satisfy Forge checkstyle `TodoComment` rule

## Commits

| Commit | Description |
|--------|-------------|
| `fix: configure Micronaut annotation processor and CLASSIC loader` | Core fix - adds annotation processor for Java sources + CLASSIC loader convention for bootJar/bootWar |
| `fix: add bootWar CLASSIC loader to Forge-generated build.gradle` | Forge template parity - bootWar was missing CLASSIC loader config |
| `chore: add Apache license header to GrailsMicronautValidator` | License header + checkstyle compliance |
| `fix: exclude Spring Boot DevTools for Micronaut apps in Forge` | Prevents devtools auto-application for Micronaut apps |
| `docs: document Micronaut annotation processor and CLASSIC loader` | Upgrade guide notes |
| `Address PR review feedback` | Comprehensive ersatz tests, plugin @Singleton beans, docs updates |
| `Exhaustive ersatz integration tests for all Micronaut client patterns` | 43 new tests covering every client integration pattern |
| `test: add Groovy-only Micronaut test module` | New module validating grails-micronaut works without annotationProcessor deps or Java files |

## Test Coverage

**121 integration tests passing** across 13 specs in two test modules:

#### Ersatz-mocked HTTP client tests (70 tests)

| Spec | Tests | Coverage |
|------|-------|----------|
| `MicronautErsatzRoundtripSpec` | 17 | Full roundtrip: HTTP -> Grails controller -> service -> @Client -> ersatz. All CRUD operations, error handling, sequential responses, custom headers, large payloads |
| `MicronautErsatzAdvancedSpec` | 27 | Every HTTP method (GET/POST/PUT/DELETE/PATCH/HEAD/OPTIONS/ANY), @QueryValue, @Header (method + class-level), @CookieValue, Basic Auth, response cookies, plain text, XML, delayed responses, sequential responses (503->503->200), request listeners, call count verification, multi-client coexistence, service orchestration |
| `MicronautErsatzPatternSpec` | 16 | CompletableFuture<T> returns (GET/POST/DELETE), void return, @Client(path=) base path, @ClientFilter + @RequestFilter auto-header injection, @Retryable with sequential failure/success, bean resolution, full roundtrips for async/path/filtered patterns |
| `MicronautDeclarativeClientSpec` | 10 | Direct declarative client operations against ersatz |

#### Bean integration tests (35 tests)

| Spec | Tests | Coverage |
|------|-------|----------|
| `MicronautBeanDuplicationSpec` | 9 | No bean duplication, cross-context singleton identity |
| `MicronautQualifierSpec` | 7 | @Named, @Primary, collection injection |
| `MicronautContextSpec` | 6 | Context bridge, lifecycle, cross-context lookup |
| `MicronautBeanTypesSpec` | 5 | Java @Singleton, @Factory/@Bean, @ConfigurationProperties |
| `MicronautPluginBeanSpec` | 5 | Plugin-contributed @Singleton beans in Spring + Micronaut contexts |
| `BeanInjectionServiceSpec` | 3 | Micronaut bean injection into Grails services |

### `grails-test-examples-micronaut-groovy-only` (16 tests)

| Spec | Tests | Coverage |
|------|-------|----------|
| `BeanInjectionServiceSpec` | 3 | Micronaut bean injection into Grails services (Groovy-only) |
| `MicronautContextSpec` | 6 | Micronaut/Spring context coexistence, bean lookup, lifecycle (Groovy-only) |
| `MicronautQualifierSpec` | 7 | @Named, @Primary, custom @Qualified, collection injection (Groovy-only) |

This module has **no Java source files** and **no `annotationProcessor` dependencies** in its `build.gradle`. It validates the documentation claim that the Grails Gradle plugin automatically applies the required Micronaut annotation processors when `grails-micronaut` is present.

### Micronaut client patterns tested

| Pattern | Client Interface | Language |
|---------|-----------------|----------|
| @Get, @Post, @Put, @Delete, @PathVariable, @Body | `MicronautTestClient` | Groovy |
| @Patch, @QueryValue, @Header, @Head, @Options, @CookieValue, text/plain | `MicronautAdvancedClient` | Groovy |
| Class-level @Header (auto on all requests) | `MicronautHeaderClient` | Groovy |
| CompletableFuture<T>, void return type | `MicronautReactiveClient` | Groovy |
| @Client(id, path=) base path / API versioning | `MicronautPathClient` | Groovy |
| @ClientFilter + @RequestFilter auto-header injection | `AuthTokenClientFilter` + `MicronautFilteredClient` | Java + Groovy |
| @Retryable(attempts, delay) with AOP processing | `MicronautRetryableClient` | Java |

### Ersatz mock server features exercised

- Request matching: method, path, query params, headers, cookies, body
- Response config: status codes, JSON/text/XML bodies, headers, cookies, delays
- Sequential responses: different response per call (last repeats)
- Call count verification: exact count assertions
- Request listeners: capture and inspect request details
- Error simulation: 401, 403, 404, 429, 500, 502, 503

### Forge tests

**4 tests passing** in `SpringBootDevToolsSpec` - verifies devtools exclusion for Micronaut apps.

## Build Verification

| Project | Status |
|---------|--------|
| `grails-gradle` (plugins) | :white_check_mark: BUILD SUCCESSFUL |
| `grails-forge` (checkstyle) | :white_check_mark: BUILD SUCCESSFUL |
| `grails-doc` (guide) | :white_check_mark: BUILD SUCCESSFUL |
| `codeStyle` (main project) | :white_check_mark: BUILD SUCCESSFUL |
| `grails-test-examples-micronaut:integrationTest` | :white_check_mark: 105/105 PASSED |
| `grails-test-examples-micronaut-groovy-only:integrationTest` | :white_check_mark: 16/16 PASSED |

## Remaining Gaps (Out of Scope)

These are known limitations of the current Micronaut integration, not addressed by this PR:

- Groovy incremental compilation may re-trigger AST transforms on unchanged files (Groovy compiler limitation)
- No `bootRun` CLASSIC loader needed (only affects packaged archives)

Fixes #15207
Fixes #15211
Fixes #11599

### CODE REVIEW

**Comment by jamesfredley** [comment]
@sbglasius @jdaugherty I think this is a bit closer to where we need it, but do not fully understand the finish line.

File: grails-test-examples/micronaut/grails-app/controllers/micronaut/MicronautTestController.groovy [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+    @Autowired
+    NamedService namedService
+
+    def index() {
+        render(contentType: 'application/json', text: [
+            javaMessage: javaSingletonService.message,
+            factoryName: factoryCreatedService.name,
+            appName: appConfig.name,
+            namedService: namedService.name
+        ])
```
[the remark this answers is not in the document]
Comment (jamesfredley) [reply grails-test-examples/micronaut/grails-app/controllers/micronaut/MicronautTestController.groovy]: Fixed - changed to `render([...] as JSON)` with `import grails.converters.JSON`, matching the established pattern used across the codebase.

File: grails-test-examples/micronaut/src/integration-test/groovy/micronaut/MicronautBeanTypesSpec.groovy [hunk 2]
```diff
@@ -0,0 +1,84 @@
...
+    }
+
+    void "Factory-created bean is a singleton instance"() {
+        when:
+        def first = factoryCreatedService
+        def second = factoryCreatedService
+
+        then: "same instance is returned (factory method annotated with @Singleton)"
+        first.is(second)
+    }
```
[the remark this answers is not in the document]
Comment (jamesfredley) [reply grails-test-examples/micronaut/src/integration-test/groovy/micronaut/MicronautBeanTypesSpec.groovy:87]: Fixed - both singleton tests now use `applicationContext.getBean()` to retrieve the bean twice independently, which properly verifies singleton scope.

File: grails-test-examples/micronaut/src/main/java/bean/injection/JavaSingletonService.java [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+interface JavaMessageProvider {
+
+    String getMessage();
+
+}
+
+@Singleton
+public class JavaSingletonService implements JavaMessageProvider {
+
+    @Override
```
[the remark this answers is not in the document]
Comment (jamesfredley) [reply grails-test-examples/micronaut/src/main/java/bean/injection/JavaSingletonService.java]: Fixed - made `JavaMessageProvider` public and added a new test `"Java @Singleton bean is resolvable by its interface type"` in `MicronautBeanTypesSpec` that exercises interface-type injection, verifying the bean is found and is the same singleton instance.

File: grails-doc/src/en/guide/upgrading/upgrading60x.adoc [hunk 4]
```diff
@@ -371,6 +371,12 @@ Here's an example `gradle.properties` file:
 micronautPlatformVersion=4.9.2
 ----
 
+Please note that due to https://github.com/micronaut-projects/micronaut-spring/issues/769[this issue], Spring Boot Dev tools does not work with the micronaut integration.
```
[the remark this answers is not in the document]
Comment (jamesfredley) [reply grails-doc/src/en/guide/upgrading/upgrading60x.adoc]: Fixed - corrected to "Spring Boot DevTools" and "Micronaut integration" with the grammar tightened as suggested.

**Comment by jdaugherty** [comment]
@jamesfredley  did you checkout the mcironaut branch I pushed and compare it to these changes?  Both of these were fixed in that branch.  The problem with that branch is how do we reflect the micronaut specific beans into spring.

**Comment by jamesfredley** [comment]
@jdaugherty Yes, this branch is based on https://github.com/apache/grails-core/tree/micronaut-fixes.  Take a look at the new tests to see if they are covering all bean vs bean scenarios that were at issue.

**Comment by jdaugherty** [comment]
@jamesfredley can you add a declarative client & associated test?  You can use [mocking](https://github.com/cjstehno/ersatz) to test it actually calling an endpoint.  I suspect it's still broken with these changes.

File: grails-gradle/plugins/src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy [hunk 5]
```diff
@@ -376,10 +379,22 @@ class GrailsGradlePlugin extends GroovyPlugin {
                 }
             }
 
-            project.logger.info('Adding Micronaut annotationProcessor dependencies to project {}', project.name)
+            // Add Micronaut annotation processor for Java source files.
+            // Groovy sources are handled by micronaut-inject-groovy AST transforms (via compileOnlyApi),
+            // but Java sources require the Java annotation processor to generate BeanDefinition classes.
+            // The annotationProcessor configuration only affects compileJava tasks, not compileGroovy.
+            project.logger.info('Adding Micronaut annotationProcessor for Java sources in {}', project.name)
```
Comment (jdaugherty) [inline grails-gradle/plugins/src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy]: The annotation processors are incompatible with groovy incremental compilation and have previously never been configured.  I'd argue we shouldn't configure them and document it so that if someone wants it for java, they can have it.

Comment (jamesfredley) [reply grails-gradle/plugins/src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy]: Agreed. Removed the auto-configured annotation processors. Added a comment in the plugin noting the incompatibility with Groovy incremental compilation and pointing to the docs for manual setup.

The micronaut test example now explicitly configures the annotationProcessor deps in its own build.gradle since it has Java sources (`JavaSingletonService.java`). All 33 integration tests pass.

**Comment by jamesfredley** [comment]
@jdaugherty Added a declarative `@Client` interface (`MicronautTestClient.groovy`) and integration test (`MicronautDeclarativeClientSpec`).

Results:
- **`@Client` bean registration**: PASSES. The declarative client interface compiles via the Groovy AST transform (`micronaut-inject-groovy`) and is resolvable from the Micronaut context.
- **Micronaut `HttpClient` calling the running Grails app**: PASSES. The Micronaut HTTP stack works within Grails.

Regarding ersatz/mock endpoint testing - I opted to test against the running Grails app itself rather than a mock server, since the integration test already boots the full application. This keeps the test dependencies minimal and directly tests the Grails+Micronaut integration path.

File: grails-test-examples/micronaut/src/integration-test/groovy/micronaut/MicronautDeclarativeClientSpec.groovy [hunk 6]
```diff
@@ -0,0 +1,61 @@
...
+        def client = micronautContext.getBean(MicronautTestClient)
+
+        then: "the bean is found and implements the interface"
+        client != null
+        client instanceof MicronautTestClient
+    }
+
+    void "Micronaut HttpClient can reach the running Grails application"() {
+        given: "a Micronaut HTTP client targeting the running server"
+        def client = HttpClient.create("http://localhost:$serverPort".toURL())
```
Comment (jdaugherty) [inline grails-test-examples/micronaut/src/integration-test/groovy/micronaut/MicronautDeclarativeClientSpec.groovy:92]: I think you need to actually invoke the declarative client.  This isn't going through the load balancing path and from my experience that's the bean that isn't copied to the spring context.

Comment (jdaugherty) [reply grails-test-examples/micronaut/src/integration-test/groovy/micronaut/MicronautDeclarativeClientSpec.groovy:92]: You can use the previously mentioned https://github.com/cjstehno/ersatz server to mock the response so the client has a valid endpoint

Comment (jamesfredley) [reply grails-test-examples/micronaut/src/integration-test/groovy/micronaut/MicronautDeclarativeClientSpec.groovy:92]: Done in 782b950. The test now invokes `client.index()` through the full service discovery and load balancing path. The `@Client(id='grails-self')` resolves via `micronaut.http.services.grails-self.url` to an ersatz mock server that returns a known JSON response - the test asserts both the response content and that ersatz received exactly one request via `ersatz.verify()`.

Comment (jamesfredley) [reply grails-test-examples/micronaut/src/integration-test/groovy/micronaut/MicronautDeclarativeClientSpec.groovy:92]: Good call - used `ersatz:4.0.1` (core, not the groovy variant which has a classpath issue). The ersatz server starts on a fixed port (19876) configured in `application.yml` under the test environment as `micronaut.http.services.grails-self.url`. All 3 tests pass.

Comment (jdaugherty) [reply grails-test-examples/micronaut/src/integration-test/groovy/micronaut/MicronautDeclarativeClientSpec.groovy:92]: I'm suggesting we check in such a test so we know when this breaks in the future.

**Comment by sbglasius** [comment]
One of the issues I have seen was using a grails-plugin with Micronaut beans (`@Singleton`). I could  make another test-example project that verifies this too?

File: grails-forge/grails-forge-core/src/main/java/org/grails/forge/feature/build/gradle/templates/buildGradle.rocker.raw [hunk 7]
```diff
@@ -107,6 +107,17 @@ bootRun {
...
+tasks.named('bootJar') {
+    loaderImplementation = org.springframework.boot.loader.tools.LoaderImplementation.CLASSIC
+}
+
+tasks.named('bootWar') {
+    loaderImplementation = org.springframework.boot.loader.tools.LoaderImplementation.CLASSIC
+}
+
+}
+
```
Comment (matrei) [inline grails-forge/grails-forge-core/src/main/java/org/grails/forge/feature/build/gradle/templates/buildGradle.rocker.raw]: Do we still need these here, even if they are configured by the `GrailsGradlePlugin`?

File: grails-doc/src/en/guide/upgrading/upgrading60x.adoc [hunk 8]
```diff
@@ -371,6 +371,12 @@ Here's an example `gradle.properties` file:
 micronautPlatformVersion=4.9.2
 ----
 
+Please note that, due to https://github.com/micronaut-projects/micronaut-spring/issues/769[this issue], Spring Boot DevTools does not work with the Micronaut integration.
+
+IMPORTANT: Do **not** manually add Micronaut annotation processors (such as `micronaut-inject-java`) to your `build.gradle`. The Grails Gradle Plugin automatically configures the correct annotation processor for Java source files and uses Groovy AST transforms (`micronaut-inject-groovy`) for Groovy source files. Manually adding annotation processors may cause duplicate bean definitions or incremental compilation issues (see https://github.com/apache/grails-core/issues/15211[#15211]).
```
Comment (matrei) [inline grails-doc/src/en/guide/upgrading/upgrading60x.adoc]: Is this still correct?

**Comment by jdaugherty** [comment]
> One of the issues I have seen was using a grails-plugin with Micronaut beans (`@Singleton`). I could  make another test-example project that verifies this too?

That would test the scenario I am worried about.  Would you push updates to this PR @sbglasius

File: grails-gradle/plugins/src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy [hunk 9]
```diff
@@ -376,10 +379,13 @@ class GrailsGradlePlugin extends GroovyPlugin {
...
-            project.getDependencies().add('annotationProcessor', project.dependencies.platform("io.micronaut.platform:micronaut-platform:$micronautPlatformVersion"))
-            project.getDependencies().add('annotationProcessor', 'io.micronaut:micronaut-inject-java')
-            project.getDependencies().add('annotationProcessor', 'jakarta.annotation:jakarta.annotation-api')
+            project.logger.info('Configuring CLASSIC boot loader for Micronaut compatibility in {}', project.name)
+            project.tasks.withType(BootJar).configureEach { BootJar bootJar ->
+                bootJar.loaderImplementation.convention(LoaderImplementation.CLASSIC)
+            }
+            project.tasks.withType(BootWar).configureEach { BootWar bootWar ->
+                bootWar.loaderImplementation.convention(LoaderImplementation.CLASSIC)
+            }
```
Comment (matrei) [inline grails-gradle/plugins/src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy]:
```suggestion
            project.tasks.withType(BootArchive).configureEach {
                it.loaderImplementation.convention(LoaderImplementation.CLASSIC)
            }

```

File: grails-gradle/plugins/src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy [hunk 10]
```diff
@@ -71,7 +71,10 @@ import org.springframework.boot.gradle.dsl.SpringBootExtension
 import org.springframework.boot.gradle.plugin.ResolveMainClassName
 import org.springframework.boot.gradle.plugin.SpringBootPlugin
 import org.springframework.boot.gradle.tasks.bundling.BootArchive
+import org.springframework.boot.gradle.tasks.bundling.BootJar
+import org.springframework.boot.gradle.tasks.bundling.BootWar
```
Comment (matrei) [inline grails-gradle/plugins/src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy]:
```suggestion
```

File: grails-doc/src/en/guide/upgrading/upgrading60x.adoc (hunk 8 above)
Comment (jdaugherty) [reply grails-doc/src/en/guide/upgrading/upgrading60x.adoc]: No, it needs updated to indicate that the micronaut plugin only adds support for groovy.  Annotation Processors would need added for java & it will break the groovy incremental compilation if added.  It's best to split java from groovy in separate projects as a result.

File: grails-forge/grails-forge-core/src/main/java/org/grails/forge/feature/build/gradle/templates/buildGradle.rocker.raw (hunk 7 above)
Comment (jdaugherty) [reply grails-forge/grails-forge-core/src/main/java/org/grails/forge/feature/build/gradle/templates/buildGradle.rocker.raw]: No, we should remove them now that the plugin is handling it.

**Comment by jdaugherty** [comment]
@jamesfredley I think we can merge this once @sbglasius or you add that other test scenario (I'd like to see an actual mock using ersatz) & the rest of @matrei comments are addressed.

File: grails-test-examples/micronaut/src/integration-test/groovy/micronaut/MicronautDeclarativeClientSpec.groovy (hunk 6 above)
Comment (jamesfredley) [reply grails-test-examples/micronaut/src/integration-test/groovy/micronaut/MicronautDeclarativeClientSpec.groovy:92]: Done in 6b59b6f. Expanded the declarative client test significantly with ersatz mocking every response scenario:

**MicronautDeclarativeClientSpec** (10 tests) - direct @Client -> ersatz:
- GET, POST, PUT, DELETE with mock responses
- Path variable resolution
- 404 and 500 error handling
- Accept header via low-level HttpClient

**MicronautErsatzRoundtripSpec** (17 tests) - full HTTP roundtrip through Grails:
- HTTP client -> Grails controller -> service -> @Client -> ersatz for all CRUD ops
- Error propagation from ersatz through the entire stack
- Sequential calls to multiple ersatz-mocked endpoints
- Custom response headers, empty bodies, large JSON responses (50 items)

Also added the plugin @Singleton scenario @sbglasius suggested - see MicronautPluginBeanSpec (5 tests).

File: grails-forge/grails-forge-core/src/main/java/org/grails/forge/feature/build/gradle/templates/buildGradle.rocker.raw (hunk 7 above)
Comment (jamesfredley) [reply grails-forge/grails-forge-core/src/main/java/org/grails/forge/feature/build/gradle/templates/buildGradle.rocker.raw]: Removed in 6b59b6f per @jdaugherty's confirmation - the plugin handles it now.

File: grails-doc/src/en/guide/upgrading/upgrading60x.adoc (hunk 8 above)
Comment (jamesfredley) [reply grails-doc/src/en/guide/upgrading/upgrading60x.adoc]: Rewrote in 6b59b6f per @jdaugherty's feedback - now clarifies that the Micronaut plugin only adds Groovy support, annotation processors need to be configured separately for Java, and recommends splitting Java from Groovy in separate source sets to avoid breaking incremental compilation.

File: grails-gradle/plugins/src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy (hunk 9 above)
Comment (jamesfredley) [reply grails-gradle/plugins/src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy]: Already applied in a prior commit (6c81244).

File: grails-gradle/plugins/src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy (hunk 10 above)
Comment (jamesfredley) [reply grails-gradle/plugins/src/main/groovy/org/grails/gradle/plugin/core/GrailsGradlePlugin.groovy]: Already applied in a prior commit (749364d).

**Comment by jamesfredley** [comment]
@sbglasius Added in 6b59b6f - created a `micronaut-singleton` plugin (`grails-test-examples/plugins/micronaut-singleton/`) with a Java `@Singleton` bean (`PluginSingletonService`) and wired it into the micronaut test app.

`MicronautPluginBeanSpec` (5 tests) verifies:
- Plugin `@Singleton` bean available in Spring context
- Plugin `@Singleton` bean available in Micronaut context
- Singleton identity (same instance on repeated lookups)
- Resolvable by interface type (`PluginMessageProvider`)
- Same instance across both Spring and Micronaut contexts

All 5 pass.

**Comment by jamesfredley** [comment]
@jdaugherty All items addressed in 6b59b6f:

1. **Ersatz-mocked declarative client tests** - `MicronautDeclarativeClientSpec` (10 tests) and `MicronautErsatzRoundtripSpec` (17 tests) cover GET/POST/PUT/DELETE, error handling (404, 500, 503), custom headers, large responses, and full HTTP roundtrip through Grails (controller -> service -> @Client -> ersatz)
2. **Plugin @Singleton scenario** - `micronaut-singleton` plugin with Java `@Singleton` bean, verified in `MicronautPluginBeanSpec` (5 tests)
3. **@matrei comments** - Forge template CLASSIC loader removed, upgrade guide rewritten, BootArchive/import cleanup already done in prior commits

63 integration tests total, all passing.

File: grails-test-examples/plugins/issue-11767/build.gradle [hunk 11]
```diff
@@ -28,8 +28,12 @@ apply plugin: 'org.apache.grails.gradle.grails-plugin'
 
 dependencies {
     implementation platform(project(':grails-bom'))
-    implementation 'org.apache.grails:grails-micronaut'
     implementation 'org.apache.grails:grails-core'
+    implementation 'org.apache.grails:grails-micronaut'
+
+    annotationProcessor platform("io.micronaut.platform:micronaut-platform:$micronautPlatformVersion")
+    annotationProcessor 'io.micronaut:micronaut-inject-java'
```
Comment (jdaugherty) [inline grails-test-examples/plugins/issue-11767/build.gradle:35]: Can we make one of these apps not have java?  So we can confirm that the groovy only includes suffices?

**Review by jdaugherty — APPROVED** [review]
Only concern is we don't have a case where only the default micronaut plugin is applied - we're including the inject java too.  Can we make one of these apps not have java & then not include the inject java?
